config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

# get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants
# collection do
#   get :top
# end
# member do
#   get :chef
# end
# collection -> all restaurants aka don't need an id
# member -> one restaurant aka need the restaurant id


# link_to '', restaurants_path, method: :post
# link_to '', restaurants_path, method: :get

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations -> has_many / belongs_to
  has_many :reviews, dependent: :destroy # creates a method -> restaurant.reviews
  belongs_to :user
  # dependent destroy -> will delete the reviews along with the restaurant
  # validations
  # validates :column_name, validation_name: arg
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # creates a method -> review.restaurant
  validates :content, presence: true, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # DEVISE
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  # end

  # PUNDIT
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  # CRUD -> read WHERE
  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  # CRUD -> read - show page for a chef
  def chef
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = policy_scope(Restaurant) # Restaurant is passed to the policy_scope inside the `scope` variable
  end

  def show
    # params[:id] is coming from the URL
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    authorize @restaurant
  end

  def new
    # this is just a page for a form
    @restaurant = Restaurant.new
    authorize @restaurant # we're performing the authorization, i.e. checking if the user is allowed to do this. We're NOT allowing them just by calling `authorize``
  end

  def create
    # This actions DOES NOT have a view
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant # We authorize before saving

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # this is just a page for a form
    @restaurant = Restaurant.find(params[:id])
    authorize(@restaurant) # passing the @restaurant into the `record` variable in the policy file

    # raise 'NotAuthorizedError' unless current_user == @restaurant.user
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    # raise 'NotAuthorizedError' unless current_user == @restaurant.user
    authorize @restaurant

    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    # this is only for the form
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(restaurant: @restaurant)
    authorize @review
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id]) # pulling the id from the url
    @review = Review.new(review_params) # this is only things from the from
    @review.restaurant = @restaurant # adding the belongs_to here
    authorize @review

    
      if @review.save
        # redirect_to restaurant's page
        respond_to do |format|
          format.html { redirect_to restaurant_path(@restaurant) }
          format.json do
            # send the json with the new review and the empty form
            render json: {
              review_html: render_to_string(partial: "reviews/review", formats: :html, locals: { review: @review }),
              form_html: render_to_string(partial: "reviews/new", formats: :html, locals: { restaurant: @review.restaurant, review: Review.new })
          }.to_json
          end
        end
      else
        # display the form again
        respond_to do |format|
          format.html { render "restaurants/show", status: :unprocessable_entity }
          format.json do
            render json: {
              form_html: render_to_string(partial: "reviews/new", formats: :html, locals: { restaurant: @review.restaurant, review: @review })
          }.to_json
          end
        end
        
      end
 
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants-1188</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheChopsticks1105</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row">
        <div class="col-4 offset-4">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category.downcase %>&<%= rand(1000) %>)">
  <% if show_owner %>
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{restaurant.user.username}", class: 'avatar position-absolute top-0 end-0 m-2 border border-white' %>
  <% end %>
  <%= restaurant.name %>
  <%= link_to "", restaurant_path(restaurant), class: "card-link"  %>
</div>

app/views/restaurants/_side_info.html.erb
<div class="position-relative">
  <p>
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@restaurant.user.username}", class: 'avatar border border-white' %>
    <%= @restaurant.user.username %>
  </p>
  <p class="fw-lighter opacity-75">
    <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
  </p>
  <p class="fw-lighter opacity-75">
    <% rand(2..5).times do %>
      <i class="fas fa-dollar-sign"></i>
    <% end %>
  </p>
  <p class="fw-lighter opacity-75">
    <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
  </p>
  <div class="d-flex">
    <%# if current_user == @restaurant.user %>
    <% if policy(@restaurant).edit? %>
      <%= link_to edit_restaurant_path(@restaurant), class: 'text-dark text-decoration-none' do %>
        <i class="fas fa-pencil-alt mx-1"></i>
      <% end %>
    <% end %>
    <% if policy(@restaurant).destroy? %>
      <%= link_to restaurant_path(@restaurant), class: 'text-dark text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
        <i class="fas fa-trash mx-1"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/restaurants/chef.html.erb
<div class="container mt-3">
  <h1><%= @restaurant.chef_name %></h1>
  <p><%= @restaurant.name %></p>
  <p><%= link_to 'Show', restaurant_path(@restaurant) %></p>
</div>

app/views/restaurants/edit.html.erb
<div class="container mt-3">
  <h1>Edit Restaurant</h1>
  <!--
  <form action="/restaurants" method="post">
  </form> -->
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <% if policy(Restaurant).new? %>
      <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <div class="cards">
    <%= render @restaurants, show_owner: false %>
    <%# @restaurants.each do |restaurant| %>
      <%#= render restaurant, show_owner: false %>
      <%# `render restaurant` is the same as this line below: %>
      <%#= render 'restaurants/restaurant', restaurant: restaurant, show_owner: false %>
      <%# end %>
    </div>
  </div>

app/views/restaurants/new.html.erb
<div class="container mt-3">
  <h1>Add Restaurant</h1>
  <!--
  <form action="/restaurants" method="post">
  </form> -->
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://source.unsplash.com/featured/?<%= @restaurant.category.downcase %>&<%= rand(1000) %>/800x333);">
  <div class="container">
  </div>
</div>
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% if @restaurant.rating %>
            <% @restaurant.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - @restaurant.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= @restaurant.description %></p>
      <div class="d-flex align-items-center">
        <h3>Reviews</h3>
      </div>
      <div data-controller="insert-in-list">
        <div>
          <%= render "reviews/new", restaurant: @restaurant, review: Review.new %>
        </div>
        <div data-insert-in-list-target="list">
          <% if @restaurant.reviews.any? %>
           
            <%= render @restaurant.reviews.order(created_at: :desc) %>
  
          <% else %>
            <p>No reviews yet.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>5 Star Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/_new.html.erb
<%= simple_form_for [restaurant, review], data: { action:"submit->insert-in-list#send" } do |f| %>
  <%= f.input :content, label: false %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/reviews/_review.html.erb
 <p class="m-5">
  <i class="fa-solid fa-quote-left fa-2x"></i>
  <%= review.content %>
</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "yann.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.username || 'ssaunier'}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>